AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  RoleID:
    Description: Name of superuser of database
    Type: String
  dbPassword:
    NoEcho: true
    Description: Podaj haslo dla !Ref dbUsernamea bazy danych
    Type: String
  dbUsername:
    Description: Name of superuser of database
    Type: String

Resources:
  SQSUpdate:
    Type: 'AWS::SQS::Queue'
    Properties: {}
  prognozapodlewaniaorkiestracjaUpdateSQL:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: functions/prognoza-podlewania-orkiestracjaUpdateSQL.zip
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: !Ref RoleID
      Events:
        SQSUpdate:
          Type: SQS
          Properties:
            Queue:
              'Fn::GetAtt':
                - SQSUpdate
                - Arn
            BatchSize: 10
      Environment:
        Variables:
          STEPFUNCTION_ARN: !ImportValue maszynaStanowaUpdateDoBazy
  prognozapodlewaniapobierzWszystkieSQL:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: functions/prognoza-podlewania-pobierzWszystkieSQL.zip
      Description: ''
      MemorySize: 128
      Timeout: 20
      Role: !Ref RoleID
      Environment:
        Variables:
          SQS_URL: !Ref SQSUpdate
          db_name: DBPrognozaPodlewania
          db_table: prognozaPodlewaniaDB
          db_username: !Ref dbUsername
          fields: 'id,temp,temp_odcz,waga,data'
          limit: '100'
          password: !Ref dbPassword
          rds_host: !ImportValue rdsHost
