AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  RoleID:
    Description: Name of superuser of database
    Type: String
  apikeyICM:
    NoEcho: true
    Description: Apikey ICM
    Type: String
  apikeyOpenWeather:
    NoEcho: true
    Description: Apikey ICM
    Type: String
  apikeyAirly:
    NoEcho: true
    Description: Apikey Airly
    Type: String
  apikeyWeatherbit:
    NoEcho: true
    Description: Apikey Weatherbit
    Type: String
Resources:
  prognozapodlewaniapobierzAktualneDane:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: functions/prognoza-podlewania-pobierzAktualneDane.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::790651879093:role/LambdaFullAccess'
      Environment:
        Variables:
          SQS_URL: !Ref SQSQueue1
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: 'cron(5 0,3,6,9,12,15,18,21 * * ? *)'
  prognozapodlewaniapobierzDanePython:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: functions/prognoza-podlewania-pobierzDanePython.zip
      Description: ''
      MemorySize: 128
      Timeout: 10
      Role: 'arn:aws:iam::790651879093:role/LambdaFullAccess'
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: 'cron(6 0,6,12,18 * * ? *)'
      Environment:
        Variables:
          SQS_URL: !Ref SQSQueue1
          apikey: !Ref apikeyOpenWeather
          jednostka: C
          max: '20'  
  prognozapodlewaniaorkiestracjaZapisuSQL:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: functions/prognoza-podlewania-orkiestracjaZapisuSQL.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: !Ref RoleID
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue:
              'Fn::GetAtt':
                - SQSQueue2
                - Arn
            BatchSize: 10
      Environment:
        Variables:
          STEPFUNCTION_ARN: !ImportValue maszynaStanowaUpdateDoBazyZmienna
  SQSQueue1:
    Type: 'AWS::SQS::Queue'
    Properties: {}
  prognozapodlewaniauzupelnienieICM:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: functions/prognoza-podlewania-uzupelnienieICM.zip
      Description: ''
      MemorySize: 128
      Timeout: 20
      Role: !Ref RoleID
      Environment:
        Variables:
          SQS_URL: !Ref SQSQueue2
          apikey: !Ref apikeyICM
  prognozapodlewaniapobierzDaneICM:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: functions/prognoza-podlewania-pobierzDaneICM.zip
      Description: ''
      MemorySize: 128
      Timeout: 8
      Role: !Ref RoleID
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: cron(1 12 * * ? *)
      Environment:
        Variables:
          SQS_URL: !Ref SQSQueue2
          apikey: !Ref apikeyICM
          jednostka: 'C'
  prognozapodlewanieorkiestracjaSQSPython:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: functions/prognoza-podlewania-orkiestracjaSQSPython.zip
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: !Ref RoleID
      Events:
        SQS1:
          Type: SQS
          Properties:
            Queue:
              'Fn::GetAtt':
                - SQSQueue1
                - Arn
            BatchSize: 10
      Environment:
        Variables:
          STEPFUNCTION_ARN: !ImportValue maszynaStanowaZmienna
  SQSQueue2:
    Type: 'AWS::SQS::Queue'
    Properties: {}
  prognozapodlewaniapobierzDaneAirly:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: functions/prognoza-podlewania-pobierzDaneAirly.zip
      Description: ''
      MemorySize: 128
      Timeout: 7
      Role: !Ref RoleID
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: 'cron(1 0,3,6,9,12,15,18,21 * * ? *)'
      Environment:
        Variables:
          SQS_URL: !Ref SQSQueue2
          apikey: !Ref apikeyAirly
  prognozapodlewaniapobierzDaneWeatherbit:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      CodeUri: functions/prognoza-podlewania-pobierzDaneWeatherbit.zip
      Description: ''
      MemorySize: 128
      Timeout: 8
      Role: !Ref RoleID
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: 'cron(1 0,3,6,9,12,15,18,21 * * ? *)'
      Environment:
        Variables:
          SQS_URL: !Ref SQSQueue2
          apikey: !Ref apikeyWeatherbit